# Map drives numbers to lcec slaves
# names will determine the name of the component pins
hal_402_device_mgr:
    # update rate of publisher in Hz
    update_rate: 10
    # Drive parameters:  use this group under `ethercat_drive_params`
    ethercat_drive_params_group: joints
    drives:
      drive_1:
        instance: 1
        slave_number: 0
        hal_name: lcec.0.0
        type: inovance_is620n
      drive_2:
        instance: 2
        slave_number: 1
        hal_name: lcec.0.1
        type: inovance_is620n
      drive_3:
        instance: 3
        slave_number: 2
        hal_name: lcec.0.2
        type: inovance_is620n
      drive_4:
        instance: 4
        slave_number: 3
        hal_name: lcec.0.3
        type: inovance_is620n
      drive_5:
        instance: 5
        slave_number: 4
        hal_name: lcec.0.4
        type: inovance_is620n
      drive_6:
        instance: 6
        slave_number: 5
        hal_name: lcec.0.5
        type: inovance_is620n
