arm_id: $(arg arm_id)

hardware_settings:
  $(arg arm_id)_joint_1:
    - num: 1
    - slavenum: 0
    - gear_ratio: 151.5
    - sim_startup_position: 0.0
    - max_pos: 2.96
    - min_pos: -2.96
    - max_vel: 2.09
    - max_acc: 8
    - max_torque: 717.0
    - torque_boost: 2
    - cmd_bandwidth: 400.0
    - fb_bandwidth: 500.0
    - pos_p: 20.0
    - vel_p: 150.0
    - vel_i: 750.0
    - acc_p: 0.0
    - acc_i: 0.0
    - pos_g: 0.2
    - inertia: 7.4
    - damping: 30.0
    - friction: 34.0
    - load: 0.0
    - online_estimation: 1
  $(arg arm_id)_joint_2:
    - num: 2
    - slavenum: 1
    - gear_ratio: 100
    - sim_startup_position: 0.0
    - max_pos: 2.35
    - min_pos: -1.74
    - max_vel: 3.14
    - max_acc: 12
    - max_torque: 478.0
    - torque_boost: 2
    - cmd_bandwidth: 400.0
    - fb_bandwidth: 500.0
    - pos_p: 20.0
    - vel_p: 75.0
    - vel_i: 750.0
    - acc_p: 0.0
    - acc_i: 0.0
    - pos_g: 0.2
    - inertia: 12.0
    - damping: 14.7
    - friction: 22.0
    - load: 0.0
    - online_estimation: 1
  $(arg arm_id)_joint_3:
    - num: 3
    - slavenum: 2
    - gear_ratio: 80
    - sim_startup_position: 0.0
    - max_pos: 1.15
    - min_pos: -3.71
    - max_vel: 3.92
    - max_acc: 15
    - max_torque: 203.2
    - torque_boost: 2
    - cmd_bandwidth: 400.0
    - fb_bandwidth: 500.0
    - pos_p: 20.0
    - vel_p: 50.0
    - vel_i: 500.0
    - acc_p: 0.0
    - acc_i: 0.0
    - pos_g: 0.2
    - inertia: 2.95
    - damping: 7.6
    - friction: 7.3
    - load: 0.0
    - online_estimation: 1
  $(arg arm_id)_joint_4:
    - num: 4
    - slavenum: 3
    - gear_ratio: 104.142857143
    - sim_startup_position: 0.0
    - max_pos: 2.61
    - min_pos: -2.61
    - max_vel: 3.0
    - max_acc: 12
    - max_torque: 66.56
    - torque_boost: 2
    - cmd_bandwidth: 400.0
    - fb_bandwidth: 500.0
    - pos_p: 20.0
    - vel_p: 250.0
    - vel_i: 750.0
    - acc_p: 0.0
    - acc_i: 0.0
    - pos_g: 0.2
    - inertia: 0.2
    - damping: 3.5
    - friction: 7.6
    - load: 0.0
    - online_estimation: 1
  $(arg arm_id)_joint_5:
    - num: 5
    - slavenum: 4
    - gear_ratio: 81.0
    - sim_startup_position: 0.0
    - max_pos: 2.5
    - min_pos: -2.5
    - max_vel: 3.87
    - max_acc: 15
    - max_torque: 51.84
    - torque_boost: 2
    - cmd_bandwidth: 400.0
    - fb_bandwidth: 500.0
    - pos_p: 20.0
    - vel_p: 150.0
    - vel_i: 750.0
    - acc_p: 0.0
    - acc_i: 0.0
    - pos_g: 0.2
    - inertia: 0.12
    - damping: 1.3
    - friction: 1.7
    - load: 0.0
    - online_estimation: 1
  $(arg arm_id)_joint_6:
    - num: 6
    - slavenum: 5
    - gear_ratio: -50
    - sim_startup_position: 0.0
    - max_pos: 4.0
    - min_pos: -4.0
    - max_vel: 6.28
    - max_acc: 24
    - max_torque: 32
    - torque_boost: 2
    - cmd_bandwidth: 400.0
    - fb_bandwidth: 500.0
    - pos_p: 20.0
    - vel_p: 200.0
    - vel_i: 200.0
    - acc_p: 0.0
    - acc_i: 0.0
    - pos_g: 0.2
    - inertia: 0.02
    - damping: 0.3
    - friction: 0.8
    - load: 0.0
    - online_estimation: 1