# Map drives numbers
# names will determine the name of the component pins
hal_402_device_mgr:
    # update rate of publisher in Hz
    update_rate: 10
    # Drive parameters:  use this group under `ethercat_drive_params`
    ethercat_drive_params_group: joints
    drives:
      drive_1:
        instance: 1
        slave_number: 0
        type: sim
      drive_2:
        instance: 2
        slave_number: 1
        type: sim
      drive_3:
        instance: 3
        slave_number: 2
        type: sim
      drive_4:
        instance: 4
        slave_number: 3
        type: sim
      drive_5:
        instance: 5
        slave_number: 4
        type: sim
      drive_6:
        instance: 6
        slave_number: 5
        type: sim
